package com.ms.accounts.dto;

import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.Null;
import lombok.Data;

@Data
public class AccountDto {
    @Null(message = "Id is generated by the api")
    private Long id;

    @Null(message = "Account number is generated by the api")
    private String accountNumber;

    @Null(groups = ValidationGroups.UpdateGroup.class, message = "Account type cannot be updated")
    @NotEmpty(groups = ValidationGroups.CreationGroup.class, message = "Account type is required for creating an account")
    private String accountType;

    private String branchAddress;
}
