package com.ms.accounts.dto;

import jakarta.validation.constraints.Null;
import lombok.Data;

@Data
public class AccountDto {
    @Null(message = "Id is generated by the api")
    private Long id;

    @Null(message = "Account number is generated by the api")
    private String accountNumber;

    private String accountType;

    private String branchAddress;
}
