package com.ms.accounts.dto;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.Null;
import lombok.Data;

@Data
public class CustomerDto {
    @Null(message = "Id is generated by the api")
    private Long id;

    @NotEmpty(message = "Name should not be empty")
    private String name;

    @NotEmpty(message = "Email should not be empty")
    @Email(message = "Email is not valid")
    private String email;

    @NotEmpty(message = "Mobile number should not be empty")
    private String mobileNumber;

    private AccountDto account;
}
