package com.ms.accounts.dto;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import lombok.Data;

@Data
public class CustomerDto {
    @Null(message = "Id for customer is generated by the api")
    private Long id;

    @NotEmpty(message = "Name should not be empty")
    private String name;

    @NotEmpty(message = "Email should not be empty")
    @Email(message = "Email is not valid")
    private String email;

    @NotEmpty(message = "Mobile number should not be empty")
    @Pattern(regexp = "^\\+?[0-9]{9,15}$", message = "Mobile number should be valid and contain between 10 to 15 digits")
    private String mobileNumber;

    @Valid
    private AccountDto account;
}
