server:
  port: 8080
spring:
  application:
    name: accounts
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ms-accounts-db
    username: postgres
    password: password
  config:
    import: optional:configserver:http://localhost:8070/
  profiles:
    active: dev
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure:
        include: '*'