server:
  port: 8083

spring:
  application:
    name: accounts
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ms-accounts-db
    username: postgres
    password: password
  config:
    import: optional:configserver:http://localhost:8070/
  profiles:
    active: dev
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

# Info for eureka-server microservice registration
info:
  app:
    name: "accounts"
    description: "MS Bank Accounts rest service"
    version: "1.0.0"
